language: node_js
node_js: stable
cache:
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - git submodule update --init
before_install:
  - npm install
install:
  - npm install @semantic-release/exec 
  - npm install @semantic-release/git 
  - npm install @semantic-release/changelog 
  - npm install travis-deploy-once 
script:
  - npm run build
  - travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
    target_branch: gh-pages
  